# Generated by Django 3.2.6 on 2021-08-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('blogTitle', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('auther', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
    ]
